"""Builds the Mobilis marketing pages (ui/*.html) from one shared layout, so
the nav, head and footer stay identical on every page.

    python scripts/build-site.py

Edit the page bodies below, then re-run. The app (ui/index.html) and the
demo wall (ui/demo-wall.html) are separate and not generated here.
"""
import os

UI = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "ui")

NAV = [
    ("how-it-works.html", "How it works"),
    ("four-views.html", "Four views"),
    ("demo.html", "Demo"),
    ("roadmap.html", "Roadmap"),
    ("faq.html", "FAQ"),
    ("run-locally.html", "Run locally"),
]


def layout(file, title, description, body):
    links = "\n".join(
        f'    <a href="{href}"{" aria-current=\"page\"" if href == file else ""}>{label}</a>'
        for href, label in NAV
    )
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<meta name="description" content="{description}">
<meta name="theme-color" content="#020c16">
<link rel="icon" type="image/png" href="media/favicon.png">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{description}">
<meta property="og:image" content="media/logo-full.jpg">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Geist:wght@300..600&family=Geist+Mono:wght@400;500&display=swap">
<link rel="stylesheet" href="home.css">
</head>
<body>
<!-- Generated by scripts/build-site.py: edit the page there, then re-run it. -->

<nav class="nav">
  <a class="brand" href="home.html"><img class="brand-mark" src="media/mark.png" alt="">Mobilis</a>
  <div class="nav-links">
{links}
    <a href="https://github.com/angelraph/mobilis">GitHub</a>
  </div>
  <a class="btn btn-primary btn-sm" href="index.html">Open the app</a>
</nav>
{body}
<footer class="footer">
  <div class="ribbon"></div>
  <div class="wrap foot">
    <a class="brand" href="home.html"><img class="brand-mark" src="media/mark.png" alt="">Mobilis</a>
    <p>Collateral mobility on Canton · built for HackCanton Season 3</p>
    <div class="foot-links">
      <a href="index.html">App</a>
      <a href="demo-wall.html">Four-view wall</a>
      <a href="https://github.com/angelraph/mobilis">GitHub</a>
      <a href="https://github.com/angelraph/mobilis/tree/master/docs">Docs</a>
    </div>
  </div>
</footer>

<script src="home.js"></script>
</body>
</html>
"""


def page_hero(eyebrow, title, lede):
    return f"""
<header class="page-hero">
  <svg class="sunburst" id="sunburst" viewBox="-500 -500 1000 1000" aria-hidden="true"></svg>
  <div class="wrap">
    <p class="eyebrow">{eyebrow}</p>
    <h1>{title}</h1>
    <p class="lede">{lede}</p>
  </div>
</header>
"""


def next_link(href, label):
    return f"""
<section class="band next-band">
  <div class="wrap">
    <a class="next" href="{href}"><span class="eyebrow">Next</span><span class="next-title">{label} →</span></a>
  </div>
</section>
"""


PROBLEM = """
<section class="band light">
  <div class="wrap">
    <p class="eyebrow dark">The problem</p>
    <h2>Every collateral move is checked four times, by hand, by every party.</h2>
    <div class="grid4 reveal">
      <div class="check"><span class="check-n">01</span><h3>Eligible?</h3><p>Is this asset type allowed under the agreement?</p></div>
      <div class="check"><span class="check-n">02</span><h3>Worth?</h3><p>What is it worth after the agreed haircut?</p></div>
      <div class="check"><span class="check-n">03</span><h3>Covered?</h3><p>Is the exposure still covered after the move?</p></div>
      <div class="check"><span class="check-n">04</span><h3>Concentrated?</h3><p>Is one asset type now too much of the book?</p></div>
    </div>
    <div class="stats reveal">
      <div><p class="stat">€1.6–8B</p><p class="stat-label">a year industry-wide in manual collateral and corporate-action processing (industry estimates)</p></div>
      <div><p class="stat">46%</p><p class="stat-label">of corporate-action data still handled by hand (SIX)</p></div>
      <div><p class="stat">After</p><p class="stat-label">settlement: when breaches are found today, instead of before it</p></div>
    </div>
  </div>
</section>
"""

HOME = """
<!-- Hero: Digital Asset's sunburst, HQLAx's light headline, a Bloomberg-style ledger feed. -->
<header class="hero">
  <svg class="sunburst" id="sunburst" viewBox="-500 -500 1000 1000" aria-hidden="true"></svg>
  <div class="hero-inner">
    <p class="eyebrow">Built on Canton · HackCanton Season 3</p>
    <h1>Collateral that moves.<br><span class="ribbon-text">Rules that hold.</span></h1>
    <p class="lede">Mobilis moves collateral between a pledgor, a secured party and a custodian in one atomic transaction. The Canton ledger itself enforces eligibility, haircuts, coverage and concentration. The regulator sees a report, never anyone's book.</p>
    <div class="cta-row">
      <a class="btn btn-primary" href="demo.html">Watch the demo</a>
      <a class="btn btn-ghost" href="how-it-works.html">How it works</a>
    </div>
  </div>
  <div class="feed" aria-label="Replay of the recorded demo cycle, stamped with your local time">
    <div class="feed-head"><span class="live-dot"></span>Ledger feed <span class="feed-note">replay of the demo · your local time</span></div>
    <ol class="feed-list" id="feed"></ol>
  </div>
</header>
""" + PROBLEM + """
<section class="band">
  <div class="wrap">
    <p class="eyebrow">Explore</p>
    <h2>One rulebook. Enforced by the ledger.</h2>
    <div class="explore reveal">
      <a class="tile" href="how-it-works.html"><span class="tile-n">01</span><h3>How it works</h3><p>Propose, agree and settle. Six rules checked on-ledger, and an optimiser that works inside them.</p><span class="tile-go">Read →</span></a>
      <a class="tile" href="four-views.html"><span class="tile-n">02</span><h3>Four views</h3><p>One transaction, four slices. The regulator sees a report and nothing else.</p><span class="tile-go">See →</span></a>
      <a class="tile" href="demo.html"><span class="tile-n">03</span><h3>Demo &amp; proof</h3><p>A narrated margin cycle on a live Canton ledger, 20 ledger tests, and a measured cycle time.</p><span class="tile-go">Watch →</span></a>
      <a class="tile" href="roadmap.html"><span class="tile-n">04</span><h3>Roadmap</h3><p>From one agreement on DevNet to a custodian's whole book on MainNet.</p><span class="tile-go">Plan →</span></a>
    </div>
  </div>
</section>

<section class="band deep cta-band">
  <div class="wrap">
    <h2>See one transaction from four seats at once.</h2>
    <div class="cta-row">
      <a class="btn btn-primary" href="demo-wall.html">Open the four-view wall</a>
      <a class="btn btn-ghost" href="index.html">Try the app</a>
    </div>
  </div>
</section>
"""

HOW = page_hero(
    "How it works",
    "The rulebook lives on the ledger.",
    "Every movement is a Daml contract that passes the same checks when it is agreed, and again when it settles, against the book as it stands at that moment.",
) + """
<section class="band">
  <div class="wrap">
    <p class="eyebrow">The lifecycle</p>
    <h2>Propose. Agree. Settle.</h2>
    <div class="flow reveal">
      <div class="flow-step"><span class="flow-n">1</span><h3>Propose</h3><p>Either party proposes a delivery, substitution or return. The ledger values every asset from the agreed haircut and ignores whatever the browser sent.</p></div>
      <div class="flow-step"><span class="flow-n">2</span><h3>Agree</h3><p>The counterparty agrees, but only if the move keeps the book eligible, covered and inside its concentration limits. A bad move can't even be agreed.</p></div>
      <div class="flow-step"><span class="flow-n">3</span><h3>Settle, atomically</h3><p>The custodian settles. One asset out and one in, in a single transaction. The secured party is never unprotected for a moment.</p></div>
    </div>
    <div class="swap reveal" aria-hidden="true">
      <div class="swap-lane"><span class="token out">UST-BILL · 980,000</span></div>
      <div class="swap-core"><span>atomic</span></div>
      <div class="swap-lane"><span class="token in">CASH-USD · 925,000</span></div>
    </div>
  </div>
</section>

<section class="band deep">
  <div class="wrap">
    <p class="eyebrow">The rulebook</p>
    <h2>Eight guarantees, enforced in Daml.</h2>
    <div class="rules reveal">
      <div class="rule"><span class="rule-q">Eligible?</span><p>Rejects ineligible asset types before a move can be agreed.</p></div>
      <div class="rule"><span class="rule-q">Worth?</span><p>Computes value from the agreed haircut and ignores what the caller sends.</p></div>
      <div class="rule"><span class="rule-q">Covered?</span><p>Refuses any return or swap that would leave the book short of the margin requirement.</p></div>
      <div class="rule"><span class="rule-q">Concentrated?</span><p>Caps each asset type's share of the book.</p></div>
      <div class="rule"><span class="rule-q">Margin call met?</span><p>Can only be marked fulfilled when coverage is really there.</p></div>
      <div class="rule"><span class="rule-q">Book moved?</span><p>Settlement re-checks every rule against the book as it is at that moment.</p></div>
      <div class="rule"><span class="rule-q">Prices moved?</span><p>The custodian marks prices to market and the ledger re-values the whole book at once. A drop that leaves the book short blocks every release until the pledgor tops up.</p></div>
      <div class="rule"><span class="rule-q">Preview honest?</span><p>The browser's copy of the rules is held to the ledger's answers by 16 shared test cases run on both sides.</p></div>
    </div>
    <p class="fine">Each rule has a Daml Script test (20 in total) that proves it refuses what it should. See <a href="https://github.com/angelraph/mobilis/blob/master/daml/daml/Valuation.daml">Valuation.daml</a> and <a href="https://github.com/angelraph/mobilis/blob/master/daml/daml/Tests.daml">Tests.daml</a>.</p>
  </div>
</section>

<section class="band">
  <div class="wrap split">
    <div>
      <p class="eyebrow">Collateral optimiser</p>
      <h2>AI that works inside hard rules.</h2>
      <p class="section-lede">"I need my Treasuries back for a repo." The optimiser finds the cheapest swap the agreement allows and explains why the tempting ones are illegal. The AI can only choose among rule-checked moves, and the ledger checks its choice again. The same engine proposes the cheapest top-up when prices fall, and which lots can go back when the book is over-covered.</p>
    </div>
    <div class="opt reveal">
      <div class="opt-row ok"><span>UST out → 925,000 cash in</span><b>Valid · 100% covered</b></div>
      <div class="opt-row no"><span>UST out → corporate bonds in</span><b>Over the 60% limit</b></div>
      <div class="opt-row no"><span>UST out → high-yield bonds in</span><b>Not eligible</b></div>
    </div>
  </div>
</section>
""" + next_link("four-views.html", "Four views")

VIEWS = page_hero(
    "Privacy by construction",
    "One transaction. Four different views.",
    "Canton sends each party only the contracts it is a stakeholder on. So every institution shares one correct record, and each sees only its own slice.",
) + """
<section class="band">
  <div class="wrap">
    <div class="grid4 reveal">
      <div class="view" style="--c: var(--cyan)"><h3>Pledgor</h3><p>Its agreement, the live book, every call it's party to.</p><p class="never">Never sees: the regulator's report.</p></div>
      <div class="view" style="--c: var(--indigo)"><h3>Secured party</h3><p>The same agreement and book, as the counterparty.</p><p class="never">Never sees: the regulator's report.</p></div>
      <div class="view" style="--c: var(--amber)"><h3>Custodian</h3><p>Everything operational. It settles every move and publishes the report.</p><p class="never">Nothing hidden: it's the settlement agent.</p></div>
      <div class="view view-reg" style="--c: var(--lime)"><h3>Regulator</h3><p>Only the audit report: coverage, positions, share of book, breaches.</p><p class="never">Never sees: the agreement, the schedule, any call.</p></div>
    </div>
    <p class="callout reveal">The regulator's node holds no agreement, no schedule and no call. No UI is hiding them: they were never shared with it. Tested: 0 raw contracts visible.</p>
  </div>
</section>

<section class="band deep cta-band">
  <div class="wrap">
    <h2>Watch all four seats update from one transaction.</h2>
    <div class="cta-row">
      <a class="btn btn-primary" href="demo-wall.html">Open the four-view wall</a>
      <a class="btn btn-ghost" href="demo.html">Watch the narrated demo</a>
    </div>
  </div>
</section>
""" + next_link("demo.html", "Demo &amp; proof")

DEMO = page_hero(
    "The demo",
    "One margin cycle, live on a Canton ledger.",
    "A narrated walkthrough recorded through the real interface: a delivery, a margin call the ledger won't let anyone fake, the optimiser's swap, a bad move refused, and the regulator's view.",
) + """
<section class="band">
  <div class="wrap">
    <div class="video reveal">
      <video src="media/mobilis-demo.mp4" poster="media/demo-poster.jpg" controls preload="metadata" playsinline></video>
    </div>
    <p class="fine">3 min 26 s · recorded from a local Canton sandbox through the real UI. <a href="demo-wall.html">Open the four views</a> with sample data, or <a href="https://github.com/angelraph/mobilis">run it yourself</a>.</p>
  </div>
</section>

<section class="band deep">
  <div class="wrap">
    <p class="eyebrow">Proof</p>
    <h2>Built, tested and measured.</h2>
    <div class="grid4 reveal">
      <div class="proof"><p class="big" data-count="20">20</p><p>Daml tests passing, plus 16 rulebook cases checked on both ledger and browser</p></div>
      <div class="proof"><p class="big">~2s</p><p>ledger time for a full margin cycle (3 runs, local sandbox)</p></div>
      <div class="proof"><p class="big" data-count="8">8</p><p>guarantees enforced on-ledger, including price marks</p></div>
      <div class="proof"><p class="big">0</p><p>raw contracts visible to the regulator</p></div>
    </div>
  </div>
</section>
""" + next_link("roadmap.html", "Roadmap")

ROADMAP = page_hero(
    "Roadmap",
    "From one agreement to the whole book.",
    "Where Mobilis is today, and the path from a sandbox to a custodian's whole book on Canton MainNet.",
) + """
<section class="band">
  <div class="wrap">
    <ol class="timeline reveal">
      <li class="done"><span class="when">Oct 2026 · Built</span><h3>The rulebook MVP</h3><p>On-ledger valuation with custodian price marks, coverage, concentration limits and settlement re-checks, a margin-call lifecycle, returns, the collateral optimiser with top-up and return suggestions, the regulator report, 20 ledger tests and 16 shared parity cases.</p></li>
      <li><span class="when">Q4 2026</span><h3>DevNet</h3><p>Move to Canton 3.x and the JSON Ledger API v2, real authentication, one agreement running across separate participant nodes.</p></li>
      <li><span class="when">Q1 2027</span><h3>Design-partner pilot</h3><p>One custodian and one of its pledgor clients. A market-data feed behind the custodian's price marks, tokenised holdings via the Canton token standard, cycle time measured against today's process.</p></li>
      <li><span class="when">Q2 2027</span><h3>Portfolio scale</h3><p>Many agreements per custodian, netting across agreements, intraday margin, and portfolio-level optimisation.</p></li>
      <li><span class="when">H2 2027</span><h3>Production</h3><p>MainNet, Featured App status, and more custodians and triparty agents.</p></li>
    </ol>
    <p class="fine">A plan, not a promise. Dates after October 2026 depend on the pilot partner. Full detail in <a href="https://github.com/angelraph/mobilis/blob/master/docs/ROADMAP.md">docs/ROADMAP.md</a>.</p>
  </div>
</section>
""" + next_link("faq.html", "FAQ")

FAQ = page_hero(
    "FAQ",
    "Questions judges ask.",
    "Plain answers about the idea, the technology, the AI and the business. More in <a href=\"https://github.com/angelraph/mobilis/blob/master/docs/FAQ.md\">docs/FAQ.md</a>.",
) + """
<section class="band">
  <div class="wrap narrow">
    <div class="faq">
      <details><summary>What is collateral, and what is "mobility"?</summary><p>When one institution lends to another, the borrower pledges assets (bonds, cash) as security. Values change daily, so the lender calls for more (a margin call), and the borrower often wants an asset back and offers a replacement (a substitution). Mobility means moving that collateral quickly and safely. Today it runs on spreadsheets and email.</p></details>
      <details><summary>Is this really running on Canton?</summary><p>Yes. The rules are Daml smart contracts, and the demo video was recorded from a Canton sandbox through the real UI over the JSON API. The public preview uses sample data because a static host can't run a ledger. DevNet deployment is the next milestone.</p></details>
      <details><summary>What does the AI actually do? Can it move assets?</summary><p>No, it can't move anything. The optimiser lists every swap the agreement's rules allow and scores each one by funding cost. The AI picks one of those and explains the choice. A person proposes it, the counterparty agrees and the custodian settles, and the ledger re-checks it at each step. With no AI available, the best-scoring valid move is used.</p></details>
      <details><summary>How can the regulator see a report but not the book?</summary><p>Canton only sends a party the contracts it is a stakeholder on. The regulator is an observer on the audit report contract and nothing else, so its node never receives the agreement, the schedule or the calls. The tests query the ledger as the regulator and assert zero.</p></details>
      <details><summary>What happens when prices fall?</summary><p>The custodian, as valuation agent, marks prices to market on the ledger, and every posted lot is re-valued in the same transaction. If that leaves the book short, the ledger refuses any return or swap that releases value, a margin call can't be marked fulfilled, and the pledgor's screen proposes the cheapest top-up that restores full coverage. The regulator's next report states which marks its figures use.</p></details>
      <details><summary>How do you know the browser's suggestions match the ledger?</summary><p>The optimiser and the previews run a JavaScript copy of the rulebook. Sixteen shared test cases are run against both that copy and the ledger's own Daml rulebook, and both must give the same answer. Whatever the browser suggests is checked again by the ledger anyway.</p></details>
      <details><summary>What if the book changes after a swap is agreed?</summary><p>Settlement re-runs every rule against the book as it stands at that moment. If a margin call landed in between and the swap would now leave the book short, settlement is refused. That case has its own test.</p></details>
      <details><summary>Who pays for this?</summary><p>Custodians and triparty agents. They carry the operational cost and the regulatory exposure today. The model is a platform fee per custodian plus a fee per active agreement, which we are validating in interviews.</p></details>
      <details><summary>Why not a public blockchain, or a shared database?</summary><p>Collateral books are confidential, so a public chain exposes too much. A shared database needs one party everyone trusts to run it. Canton gives each party its own node, shares only what each is entitled to see, and settles multi-party moves atomically.</p></details>
      <details><summary>What was built during the hackathon?</summary><p>A first version existed before the delivery phase and is tagged <code>pre-hackathon-baseline</code> in the repo. The on-ledger valuation and price marks, coverage, concentration limits, settlement re-check, margin-call lifecycle, returns, optimiser, tests and this interface were built during it. The README lists everything.</p></details>
    </div>
  </div>
</section>

<section class="band deep cta-band">
  <div class="wrap">
    <h2>Still curious? Read the code.</h2>
    <div class="cta-row">
      <a class="btn btn-primary" href="https://github.com/angelraph/mobilis">GitHub repository</a>
      <a class="btn btn-ghost" href="demo.html">Watch the demo</a>
    </div>
  </div>
</section>
"""

RUN = page_hero(
    "Run it yourself",
    "A real Canton ledger, on your machine.",
    "This website runs on sample data, because a static host can't run a ledger. These steps start a real Canton ledger locally and connect the same interface to it, so every button runs a real Daml transaction. About 10 minutes the first time.",
) + """
<section class="band">
  <div class="wrap narrow">
    <ol class="steps">
      <li>
        <h3>Install the prerequisites (once)</h3>
        <p><b>Git</b> (<a href="https://git-scm.com">git-scm.com</a>; on Windows this also gives you <b>Git Bash</b>, which you use for every command below), <b>Java 17</b> (<a href="https://adoptium.net">adoptium.net</a>) and the <b>Daml SDK 2.10.6</b>. On macOS or Linux:</p>
        <div class="code"><pre><code>curl -sSL https://get.daml.com/ | sh -s 2.10.6</code></pre><button class="copy" type="button">Copy</button></div>
        <p>On Windows, use the installer from <a href="https://docs.daml.com/getting-started/installation.html">docs.daml.com</a>. Then open a new terminal and check:</p>
        <div class="code"><pre><code>java -version
daml version</code></pre><button class="copy" type="button">Copy</button></div>
      </li>
      <li>
        <h3>Get the code</h3>
        <div class="code"><pre><code>git clone https://github.com/angelraph/mobilis.git
cd mobilis</code></pre><button class="copy" type="button">Copy</button></div>
      </li>
      <li>
        <h3>Run the tests <span class="opt-tag">optional</span></h3>
        <div class="code"><pre><code>cd daml
daml test
cd ..</code></pre><button class="copy" type="button">Copy</button></div>
        <p>The setup scenario, all 20 tests and the parity check should finish with <code>ok</code>. For the browser side: <code>node --test ui/rules.test.js</code>.</p>
      </li>
      <li>
        <h3>Start the ledger</h3>
        <div class="code"><pre><code>sh scripts/demo-ledger.sh</code></pre><button class="copy" type="button">Copy</button></div>
        <p>It builds the Daml model, starts a Canton sandbox, creates the four parties with an empty agreement, and serves the interface. Wait for <code>Demo ledger ready</code>. Keep that terminal open, and press Ctrl+C in it to stop.</p>
      </li>
      <li>
        <h3>Open the interface</h3>
        <p>All four roles on one screen: <code>http://localhost:7575/ui/demo-wall.html</code><br>
        One role per tab: <code>http://localhost:7575/ui/index.html?role=Pledgor</code> (or <code>SecuredParty</code>, <code>Custodian</code>, <code>Regulator</code>).</p>
      </li>
      <li>
        <h3>Walk through the demo</h3>
        <ol class="walk">
          <li><b>Pledgor</b> delivers <code>UST-BILL</code>, face <code>1000000</code>: the ledger values it at 980,000. <b>Secured party</b> agrees, <b>custodian</b> settles.</li>
          <li><b>Secured party</b> calls margin for <code>1400000</code>; the <b>custodian</b> applies it. Coverage drops to 70%, and <b>Mark fulfilled</b> is refused.</li>
          <li><b>Pledgor</b> delivers <code>IG-CORP-BOND</code>, face <code>500000</code>. Agree and settle, and now the margin call can be fulfilled.</li>
          <li><b>Pledgor</b> uses the <b>Collateral optimiser</b> ("Get back UST-BILL", then <b>Suggest</b>) and proposes the swap. Agree and settle.</li>
          <li><b>Pledgor</b> proposes <code>IG-CORP-BOND</code> → <code>CASH-USD</code>, face <code>100</code>. The <b>secured party</b> clicks Agree, and the ledger refuses it.</li>
          <li><b>Custodian</b> marks <code>IG-CORP-BOND</code> at <code>80</code> in <b>Mark to market</b>. The book re-values and falls short, and the <b>pledgor</b>'s <b>Collateral actions</b> card proposes the cheapest top-up.</li>
          <li><b>Custodian</b> generates the audit report. The <b>regulator</b> sees that report and nothing else.</li>
        </ol>
      </li>
    </ol>
    <div class="note">
      <h3>Good to know</h3>
      <ul>
        <li>The AI features are optional. Without an API key, the optimiser uses its rules engine and everything still works. To turn the AI on: <code>cd proxy</code>, put <code>OPENAI_API_KEY=…</code> in <code>.env</code>, then run <code>node server.js</code>.</li>
        <li>The first click after a fresh start can take up to 30 seconds while the ledger warms up.</li>
        <li><code>daml: command not found</code>? Open a new terminal. On Windows, use Git Bash.</li>
        <li>Every start is a fresh, empty ledger. The full guide is in <a href="https://github.com/angelraph/mobilis/blob/master/docs/RUN-LOCALLY.md">docs/RUN-LOCALLY.md</a>.</li>
      </ul>
    </div>
  </div>
</section>
"""

PAGES = [
    ("home.html", "Mobilis · collateral mobility on Canton", "Collateral that moves. Rules that hold. Mobilis moves collateral in one atomic Canton transaction, with every rule enforced by the ledger.", HOME),
    ("how-it-works.html", "How it works · Mobilis", "Propose, agree, settle: six collateral rules enforced by the Canton ledger, and an optimiser that works inside them.", HOW),
    ("four-views.html", "Four views · Mobilis", "One transaction, four views: each party sees only its slice, and the regulator sees a report and nothing else.", VIEWS),
    ("demo.html", "Demo · Mobilis", "A narrated margin cycle recorded on a live Canton ledger, with tests and a measured cycle time.", DEMO),
    ("roadmap.html", "Roadmap · Mobilis", "From one agreement on DevNet to a custodian's whole book on Canton MainNet.", ROADMAP),
    ("run-locally.html", "Run locally · Mobilis", "Run a real Canton ledger with Mobilis on your own machine in a few steps.", RUN),
    ("faq.html", "FAQ · Mobilis", "Plain answers about Mobilis: the idea, the technology, the AI and the business.", FAQ),
]

for file, title, desc, body in PAGES:
    with open(os.path.join(UI, file), "w", encoding="utf-8", newline="\n") as f:
        f.write(layout(file, title, desc, body))
    print("wrote", file)
