"""Generate daml/daml/ParityCases.daml from ui/parity-cases.json.

The JSON holds the rulebook cases that ui/rules.js (the browser's mirror)
must answer; this turns the same cases into a Daml Script test of the
ledger's Valuation.checkMove, so `daml test` fails if the two ever disagree.

    python scripts/gen-parity.py
"""
import json
import os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
SRC = os.path.join(ROOT, "ui", "parity-cases.json")
OUT = os.path.join(ROOT, "daml-test", "daml", "ParityCases.daml")

# Which words in the ledger's rejection message identify each rule.
RULE_TEXT = {
    "eligibility": "eligibility schedule",
    "posted": "not currently posted",
    "coverage": "below required collateral",
    "concentration": "concentration limit",
}


def dec(v):
    s = repr(float(v))
    return s if "." in s or "e" in s else s + ".0"


def asset(a):
    return f'PostedAsset with assetType = "{a["type"]}", faceValue = {dec(a["face"])}, postedValue = 0.0'


def action(a):
    if a["tag"] == "Substitution":
        return f"Substitution with outgoing = ({asset(a['outgoing'])}), incoming = ({asset(a['incoming'])})"
    return f"{a['tag']} with asset = ({asset(a['asset'])})"


def criterion(c):
    return (f'EligibilityCriterion with assetType = "{c["assetType"]}", '
            f'haircut = {c["haircut"]}, concentrationLimit = {c["concentrationLimit"]}')


data = json.load(open(SRC, encoding="utf-8"))
lines = [
    "-- GENERATED by scripts/gen-parity.py from ui/parity-cases.json. Do not edit by hand.",
    "-- Holds the ledger rulebook (Valuation.checkMove) to the same answers as the",
    "-- browser's mirror (ui/rules.js, tested by ui/rules.test.js).",
    "module ParityCases where",
    "",
    "import DA.Assert ((===))",
    "import DA.Text (isInfixOf)",
    "import Daml.Script",
    "import Types",
    "import qualified Valuation as V",
    "",
    "parityCriteria : [EligibilityCriterion]",
    "parityCriteria =",
    "  [ " + "\n  , ".join(criterion(c) for c in data["criteria"]),
    "  ]",
    "",
    "expectOk : Text -> Decimal -> Either Text [PostedAsset] -> Script ()",
    "expectOk _ total (Right s) = V.totalPosted s === total",
    'expectOk name _ (Left err) = abort (name <> ": expected ok, got " <> err)',
    "",
    "expectRejected : Text -> Text -> Either Text [PostedAsset] -> Script ()",
    "expectRejected name needle (Left err) =",
    '  if needle `isInfixOf` err then pure () else abort (name <> ": wrong rule: " <> err)',
    'expectRejected name _ (Right _) = abort (name <> ": expected a rejection")',
    "",
    "test_parity : Script ()",
    "test_parity = do",
]
for c in data["cases"]:
    prices = "[" + ", ".join(f'("{t}", {dec(p)})' for t, p in c["prices"]) + "]"
    sched = "[" + ", ".join(f"({asset(a)})" for a in c["schedule"]) + "]"
    call = f"(V.checkMove parityCriteria {prices} {dec(c['required'])} {sched} ({action(c['action'])}))"
    if c["expect"]["ok"]:
        lines.append(f'  expectOk "{c["name"]}" {dec(c["expect"]["total"])} {call}')
    else:
        lines.append(f'  expectRejected "{c["name"]}" "{RULE_TEXT[c["expect"]["rule"]]}" {call}')
lines.append("")

with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines))
print(f"wrote {OUT} ({len(data['cases'])} cases)")
