#!/bin/sh
# Regenerates ui/config.js from the currently built DAR.
#
# A Daml package ID is a content hash of the compiled package, so it changes
# every time the Daml model is rebuilt. The UI needs the current one to
# address templates over the JSON API. Run this after every `daml build`,
# before opening the UI:
#
#   scripts/generate-config.sh
#
set -eu

cd "$(dirname "$0")/.."

DAR="daml/.daml/dist/mobilis-0.1.0.dar"
if [ ! -f "$DAR" ]; then
  echo "Could not find $DAR. Run 'daml build' from the daml/ directory first." >&2
  exit 1
fi

MANIFEST=$(unzip -p "$DAR" META-INF/MANIFEST.MF | tr -d '\r\n ')
PACKAGE_ID=$(printf '%s' "$MANIFEST" | grep -oE 'Main-Dalf:mobilis-0\.1\.0-[0-9a-f]+' | head -1 | sed -E 's/.*-([0-9a-f]+)$/\1/')

if [ -z "$PACKAGE_ID" ]; then
  echo "Could not extract a package ID from $DAR's manifest." >&2
  exit 1
fi

cat > ui/config.js <<EOF
// Generated by scripts/generate-config.sh. Do not edit by hand; re-run the
// script after every 'daml build' instead.
window.MOBILIS_CONFIG = {
  packageId: "$PACKAGE_ID",
  jsonApiBase: "", // same-origin: the JSON API serves this UI as static content
  ledgerId: "sandbox",
  applicationId: "mobilis-ui"
};
EOF

echo "Wrote ui/config.js with packageId $PACKAGE_ID"
