// Generated by scripts/generate-config.sh. Do not edit by hand; re-run the
// script after every 'daml build' instead.
window.MOBILIS_CONFIG = {
  packageId: "47600c6b0f4df220a1f0c344045ec02185598cab208342963c0f7deef5a8b0c4",
  jsonApiBase: "", // same-origin: the JSON API serves this UI as static content
  ledgerId: "sandbox",
  applicationId: "mobilis-ui"
};
