// Generated by scripts/generate-config.sh. Do not edit by hand; re-run the
// script after every 'daml build' instead.
window.MOBILIS_CONFIG = {
  packageId: "95c13e5f7f7e44e2fe42f3ccb610fdab7e38fd1e5c028dc7bdf956ec641f48ad",
  jsonApiBase: "", // same-origin: the JSON API serves this UI as static content
  ledgerId: "sandbox",
  applicationId: "mobilis-ui"
};
