// Generated by scripts/generate-config.sh. Do not edit by hand; re-run the
// script after every 'daml build' instead.
window.MOBILIS_CONFIG = {
  packageId: "a766382f06a4620bcc6773665648169aeedca90454d0fadc39bc2815264e9ce5",
  jsonApiBase: "", // same-origin: scripts/serve-ui.js serves the UI and forwards /v2 to the ledger
  apiVersion: "v2", // "v2" = Canton 3.x JSON Ledger API
  noAuth: true, // the local sandbox runs without auth; DevNet will not
  ledgerId: "sandbox",
  applicationId: "mobilis-ui",
  hosted: false // true on the public demo ledger (shared, resets on a schedule)
};
