"use strict";

/*
 * Mobilis collateral rules, JavaScript mirror of daml/daml/Valuation.daml.
 *
 * Used for two things only: previewing what the ledger will compute, and
 * searching for moves worth suggesting (substitutions, returns, top-ups).
 * It is never the authority. Every suggestion becomes an ordinary
 * CollateralAgreement_ProposeCall, and the ledger re-runs the real rulebook
 * (Valuation.checkMove) at Agree and again at Settle.
 *
 * ui/parity-cases.json holds cases that both this file (ui/rules.test.js)
 * and the Daml rulebook (daml/daml/ParityCases.daml, generated by
 * scripts/gen-parity.py) must answer identically.
 *
 * Loaded as a plain <script> in the UI (window.MobilisRules) and with
 * require() in proxy/server.js and the tests.
 */

(function (root, factory) {
  if (typeof module === "object" && module.exports) module.exports = factory();
  else root.MobilisRules = factory();
})(typeof self !== "undefined" ? self : this, function () {
  const num = (v) => (typeof v === "string" ? parseFloat(v) : v);
  // Daml Decimal has 10 decimal places; round the same way so totals compare exactly.
  const dec = (v) => Math.round(v * 1e10) / 1e10;

  function criterionFor(criteria, assetType) {
    return criteria.find((c) => c.assetType === assetType) || null;
  }

  // prices: [[assetType, price], ...] or [{_1, _2}, ...] as the JSON API sends tuples.
  function priceFor(prices, assetType) {
    for (const p of prices || []) {
      const t = Array.isArray(p) ? p[0] : p._1;
      const v = Array.isArray(p) ? p[1] : p._2;
      if (t === assetType) return num(v);
    }
    return 1;
  }

  function valueAsset(criteria, asset, prices) {
    const c = criterionFor(criteria, asset.assetType);
    const face = num(asset.faceValue);
    return {
      assetType: asset.assetType,
      faceValue: face,
      postedValue: c ? dec(face * priceFor(prices, asset.assetType) * (1 - num(c.haircut))) : 0,
    };
  }

  function totalPosted(schedule) {
    return dec(schedule.reduce((sum, a) => sum + num(a.postedValue), 0));
  }

  function concentrations(schedule) {
    const total = totalPosted(schedule);
    const byType = {};
    for (const a of schedule) byType[a.assetType] = (byType[a.assetType] || 0) + num(a.postedValue);
    const out = {};
    for (const [t, v] of Object.entries(byType)) out[t] = total ? v / total : 0;
    return out;
  }

  function sameLot(a, b) {
    return a.assetType === b.assetType && num(a.faceValue) === num(b.faceValue);
  }

  /*
   * The rulebook: same four rules, same order, same messages' substance as
   * Valuation.checkMove. action = { tag: "Delivery" | "Return" | "Substitution",
   * asset? , outgoing?, incoming? } with assets as { assetType, faceValue }.
   * Returns { ok: true, schedule } or { ok: false, rule, reason }.
   */
  function checkMove({ criteria, prices, required, schedule, action }) {
    const req = num(required);
    const posted = schedule.map((a) => valueAsset(criteria, a, prices));
    const v = (a) => valueAsset(criteria, a, prices);
    const incoming = action.tag === "Delivery" ? [v(action.asset)] : action.tag === "Substitution" ? [v(action.incoming)] : [];
    const outgoing = action.tag === "Return" ? [v(action.asset)] : action.tag === "Substitution" ? [v(action.outgoing)] : [];

    const bad = incoming.find((a) => !criterionFor(criteria, a.assetType));
    if (bad) return { ok: false, rule: "eligibility", reason: `${bad.assetType} is not on the agreed eligibility schedule` };

    const missing = outgoing.find((o) => !posted.some((p) => sameLot(o, p)));
    if (missing) return { ok: false, rule: "posted", reason: `${missing.assetType} being released is not currently posted` };

    let next = posted.slice();
    for (const o of outgoing) {
      const i = next.findIndex((p) => sameLot(o, p));
      next.splice(i, 1);
    }
    next = next.concat(incoming);

    const newTotal = totalPosted(next);
    if (outgoing.length && newTotal < req) {
      return { ok: false, rule: "coverage", reason: `would leave posted value ${newTotal.toFixed(2)} below required ${req.toFixed(2)}` };
    }

    const shares = concentrations(next);
    const over = incoming.find((a) => {
      const c = criterionFor(criteria, a.assetType);
      return shares[a.assetType] > num(c.concentrationLimit);
    });
    if (over) {
      const limit = num(criterionFor(criteria, over.assetType).concentrationLimit);
      return { ok: false, rule: "concentration", reason: `${over.assetType} would be ${(shares[over.assetType] * 100).toFixed(1)}% of the book, over its ${(limit * 100).toFixed(0)}% limit` };
    }
    return { ok: true, schedule: next };
  }

  // Kept for callers that only check substitutions.
  function checkSubstitution(criteria, required, schedule, outgoing, incoming, prices) {
    return checkMove({ criteria, prices, required, schedule, action: { tag: "Substitution", outgoing, incoming } });
  }

  const costOf = (inventory, t) => {
    const lot = (inventory || []).find((l) => l.assetType === t);
    return lot ? num(lot.costBps) : 0;
  };

  // Smallest face value (rounded up to 1,000) of an asset that posts at least `need`.
  function faceToPost(criteria, prices, assetType, need) {
    const c = criterionFor(criteria, assetType);
    if (!c) return null;
    const perUnit = priceFor(prices, assetType) * (1 - num(c.haircut));
    return Math.max(1000, Math.ceil(need / perUnit / 1000) * 1000);
  }

  /*
   * One-for-one substitutions: each posted lot out, each inventory lot in,
   * sized to the smallest face that keeps the book covered, scored by the
   * annual funding benefit (outgoing value x its costBps minus incoming
   * value x its costBps). Returns every candidate, valid or not, so the UI
   * can show why the tempting-but-illegal moves were ruled out.
   */
  function suggestSubstitutions({ criteria, prices, required, schedule, inventory, release }) {
    const req = num(required);
    const posted = schedule.map((a) => valueAsset(criteria, a, prices));
    const out = [];
    for (const outgoing of posted) {
      if (release && outgoing.assetType !== release) continue;
      const remaining = totalPosted(posted) - outgoing.postedValue;
      for (const lot of inventory) {
        if (lot.assetType === outgoing.assetType) continue;
        const need = Math.max(0, req - remaining);
        const face = criterionFor(criteria, lot.assetType) ? faceToPost(criteria, prices, lot.assetType, need) : num(lot.available);
        const incoming = valueAsset(criteria, { assetType: lot.assetType, faceValue: face }, prices);
        const check = face > num(lot.available)
          ? { ok: false, reason: `needs ${face.toLocaleString()} face of ${lot.assetType}, only ${num(lot.available).toLocaleString()} available` }
          : checkMove({ criteria, prices, required: req, schedule: posted, action: { tag: "Substitution", outgoing, incoming } });
        out.push({
          outgoing,
          incoming,
          valid: check.ok,
          reason: check.ok ? null : check.reason,
          annualBenefit: (outgoing.postedValue * costOf(inventory, outgoing.assetType) - incoming.postedValue * costOf(inventory, lot.assetType)) / 10000,
          coverageAfter: check.ok && req > 0 ? totalPosted(check.schedule) / req : null,
        });
      }
    }
    out.sort((a, b) => (a.valid === b.valid ? b.annualBenefit - a.annualBenefit : a.valid ? -1 : 1));
    return out;
  }

  /*
   * Excess collateral: which posted lots can be returned without leaving the
   * book short. Most valuable to the pledgor first (highest funding cost).
   */
  function suggestReturns({ criteria, prices, required, schedule, inventory }) {
    const req = num(required);
    const posted = schedule.map((a) => valueAsset(criteria, a, prices));
    const excess = dec(totalPosted(posted) - req);
    const seen = new Set();
    const lots = [];
    for (const lot of posted) {
      const key = `${lot.assetType}|${lot.faceValue}`;
      if (seen.has(key)) continue;
      seen.add(key);
      const check = checkMove({ criteria, prices, required: req, schedule: posted, action: { tag: "Return", asset: lot } });
      lots.push({
        asset: lot,
        valid: check.ok,
        reason: check.ok ? null : check.reason,
        annualBenefit: (lot.postedValue * costOf(inventory, lot.assetType)) / 10000,
        coverageAfter: check.ok && req > 0 ? totalPosted(check.schedule) / req : null,
      });
    }
    lots.sort((a, b) => (a.valid === b.valid ? b.annualBenefit - a.annualBenefit : a.valid ? -1 : 1));
    return { excess, lots };
  }

  /*
   * Shortfall: the cheapest single delivery from inventory that brings the
   * book back to fully covered, inside every limit.
   */
  function suggestTopUps({ criteria, prices, required, schedule, inventory }) {
    const req = num(required);
    const posted = schedule.map((a) => valueAsset(criteria, a, prices));
    const shortfall = dec(Math.max(0, req - totalPosted(posted)));
    if (shortfall <= 0) return { shortfall: 0, options: [] };
    const options = inventory.map((lot) => {
      if (!criterionFor(criteria, lot.assetType)) {
        return { asset: { assetType: lot.assetType, faceValue: 0, postedValue: 0 }, valid: false, reason: `${lot.assetType} is not on the agreed eligibility schedule`, annualCost: 0 };
      }
      const face = faceToPost(criteria, prices, lot.assetType, shortfall);
      const asset = valueAsset(criteria, { assetType: lot.assetType, faceValue: face }, prices);
      const check = face > num(lot.available)
        ? { ok: false, reason: `needs ${face.toLocaleString()} face, only ${num(lot.available).toLocaleString()} available` }
        : checkMove({ criteria, prices, required: req, schedule: posted, action: { tag: "Delivery", asset } });
      return {
        asset,
        valid: check.ok,
        reason: check.ok ? null : check.reason,
        annualCost: (asset.postedValue * costOf(inventory, lot.assetType)) / 10000,
        coverageAfter: check.ok && req > 0 ? totalPosted(check.schedule) / req : null,
      };
    });
    options.sort((a, b) => (a.valid === b.valid ? a.annualCost - b.annualCost : a.valid ? -1 : 1));
    return { shortfall, options };
  }

  return {
    priceFor,
    valueAsset,
    totalPosted,
    concentrations,
    sameLot,
    checkMove,
    checkSubstitution,
    suggestSubstitutions,
    suggestReturns,
    suggestTopUps,
  };
});
